### ISSUE TITLE
install on remote server

### ISSUE THREAD

**Issue by anakein** [AkiraMiyakoda/mariadb-trimmean-plugin#1]
can i install your plugin into remote shared server?.

i cant compile in server only upload and download files.

thanks

**Comment by AkiraMiyakoda** [comment]
Hi @anakein,
Sorry for my late reply. 

What are the archtecture/OS of your server and client?
If both of them are the same, you can build the plugin on your client and copy it to the server's plugin directory. (typically ```/usr/lib/mysql/plugin```)

**Comment by anakein** [comment]
dont worry, thanks.
I have a shared server, I cannot install the plugin in an internal directory on the server.

Do you know how to convert the plugin into a storage procedure?
